### ISSUE TITLE
unable to install mason 

### ISSUE THREAD

**Issue by nik-v-hax** [felangel/homebrew-mason#19]
I am running on an M1, Flutter doctor is all fine, but when trying to install mason it fails. Brew throws the attached output and dart pub global activate does not but does not create a binary to run either.

dart pub global list -v
--->
FINE: Pub 2.16.1
MSG : mason 0.1.0-dev.11
MSG : melos 1.3.0
MSG : slidy 3.2.2+2
MSG : spec 0.2.0
MSG : very_good_cli 0.5.5

OUTPUT:

brew install mason
Running `brew update --preinstall`...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 1 formula.

==> Downloading https://github.com/felangel/mason/archive/refs/tags/mason_cli-v0.1.0-dev.14.tar.gz
Already downloaded: /Users/niklasvonhaxthausen/Library/Caches/Homebrew/downloads/ece17c96ab5c33ef6a1d86ebbb69fe6afc5e11f4a91a7961e22838df48af7e51--mason-mason_cli-v0.1.0-dev.14.tar.gz
==> Installing mason from felangel/mason
/opt/homebrew/Library/Taps/felangel/homebrew-mason/mason.rb:14: warning: conflicting chdir during another chdir block
==> /opt/homebrew/opt/dart/bin/pub get
==> /opt/homebrew/opt/dart/bin/dart2native -Dversion=0.1.0-dev.14 bin/mason.dart -o mason
Last 15 lines from /Users/niklasvonhaxthausen/Library/Logs/Homebrew/mason/02.dart2native:
2022-03-04 12:57:50 +0000

/opt/homebrew/opt/dart/bin/dart2native
-Dversion=0.1.0-dev.14
bin/mason.dart
-o
mason

**Comment by felangel** [comment]
Hi @nik-v-hax 👋 
Thanks for opening an issue!

I was able to reproduce this and I believe it should be resolved now. Can you re-test and let me. know if you're still experiencing issues? Thanks and sorry for the inconvenience!

**Comment by felangel** [comment]
Closing for now but please let me know if you’re still having trouble and I’m happy to reopen this 👍

**Comment by nik-v-hax** [comment]
yeah its working perfectly fine - thanks man and i'll let you know if i run into any issues
