### ISSUE TITLE
flutter_bloc_feature requires mason version > dev.57 

### ISSUE THREAD

**Issue by ctwdtw** [felangel/homebrew-mason#20]
Hi @felangel I am trying to use mason to generate code, following the README.md I got this error:
```
mason make flutter_bloc_feature --name counter --type bloc --style basic
The current mason version is 0.1.0-dev.53.
Because flutter_bloc_feature requires mason version >=0.1.0-dev.57 <0.1.0, version solving failed.
```

Would you please update the homebrew formula to dev.57, thank you.

**Comment by felangel** [comment]
Can you try uninstalling and reinstalling mason cli via homebrew? The latest version of mason_cli already supports mason dev.57.

**Comment by felangel** [comment]
Closing for now since there aren't any actionable next steps. Let me know if this is still an issue after you've upgraded your version of mason_cli.
